# Generated by Django 3.0.2 on 2020-01-24 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\d{5}\\-\\d{3}$')], verbose_name='CEP'),
        ),
    ]
