# Generated by Django 3.0.2 on 2020-01-28 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200124_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='logo',
        ),
    ]
