# Generated by Django 2.2.6 on 2019-10-30 14:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20191030_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
