# Generated by Django 2.2.6 on 2019-10-30 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_cliente_jwt_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='jwt_secret',
        ),
    ]
