# Generated by Django 2.2.6 on 2019-11-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_cliente_jwt_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendaproduto',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade'),
            preserve_default=False,
        ),
    ]
