# Generated by Django 2.2.6 on 2019-11-01 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_vendaproduto_quantidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('rating', models.FloatField(verbose_name='Rating')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_cliente', to='website.Cliente')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_loja', to='website.Loja')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='loja',
            name='avaliacoes',
            field=models.ManyToManyField(related_name='avaliacoes', through='website.Avaliacao', to='website.Cliente'),
        ),
    ]
