# Generated by Django 2.2.6 on 2019-11-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20191101_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='website/images', verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='produto',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='website/images', verbose_name='Imagem'),
        ),
    ]
