# Generated by Django 2.2.6 on 2019-11-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20191101_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao_completa',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição Completa'),
        ),
    ]
