# Generated by Django 2.2.7 on 2019-11-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_produto_descricao_completa'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='comentario',
            field=models.TextField(blank=True, null=True, verbose_name='Comentário'),
        ),
    ]
