# Generated by Django 2.2.7 on 2019-11-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20191106_1516'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together={('cliente', 'loja')},
        ),
    ]
