# Generated by Django 2.2.7 on 2019-11-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20191107_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(default='a', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loja',
            name='categorias',
            field=models.ManyToManyField(to='website.Categoria'),
        ),
    ]
