# Generated by Django 2.2.7 on 2019-11-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20191112_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='qtd_acessos',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade de acessos'),
        ),
    ]
