# Generated by Django 2.2.7 on 2019-11-12 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20191112_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome']},
        ),
    ]
