# Generated by Django 2.2.7 on 2019-11-13 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20191113_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenscarrinho',
            name='carrinho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_carrinho', to='website.Carrinho'),
        ),
    ]
