# Generated by Django 2.2.7 on 2019-11-13 14:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_auto_20191113_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor'),
        ),
    ]
