# Generated by Django 2.2.7 on 2019-11-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_carrinho_valor_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenscarrinho',
            name='quantidade',
            field=models.PositiveIntegerField(null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='itenscarrinho',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Valor'),
        ),
    ]
