# Generated by Django 2.2.7 on 2019-11-18 11:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_auto_20191113_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Rating')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentário')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_produtos', to='website.Cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_produtos', to='website.Produto')),
            ],
            options={
                'verbose_name': 'Avaliação do Produto',
                'verbose_name_plural': 'Avaliações dos Produtos',
                'unique_together': {('cliente', 'produto')},
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='rating',
            field=models.ManyToManyField(through='website.AvaliacaoProduto', to='website.Cliente'),
        ),
    ]
