# Generated by Django 2.2.7 on 2019-11-18 12:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_auto_20191118_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoLoja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Rating')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentário')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Cliente')),
            ],
            options={
                'verbose_name': 'Avaliação da Loja',
                'verbose_name_plural': 'Avaliações das Lojas',
            },
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='rating',
            new_name='avaliacoes',
        ),
        migrations.AlterField(
            model_name='avaliacaoproduto',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Cliente'),
        ),
        migrations.AlterField(
            model_name='avaliacaoproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Produto'),
        ),
        migrations.AlterField(
            model_name='loja',
            name='avaliacoes',
            field=models.ManyToManyField(through='website.AvaliacaoLoja', to='website.Cliente'),
        ),
        migrations.DeleteModel(
            name='Avaliacao',
        ),
        migrations.AddField(
            model_name='avaliacaoloja',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Loja'),
        ),
        migrations.AlterUniqueTogether(
            name='avaliacaoloja',
            unique_together={('cliente', 'loja')},
        ),
    ]
