# Generated by Django 2.2.7 on 2019-11-18 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_auto_20191118_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaoloja',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_loja', to='website.Cliente'),
        ),
        migrations.AlterField(
            model_name='avaliacaoloja',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_loja', to='website.Loja'),
        ),
        migrations.AlterField(
            model_name='avaliacaoproduto',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_produto', to='website.Cliente'),
        ),
        migrations.AlterField(
            model_name='avaliacaoproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_produto', to='website.Produto'),
        ),
    ]
