# Generated by Django 2.2.7 on 2019-11-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_auto_20191118_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='loja',
        ),
    ]
