# Generated by Django 2.2.7 on 2019-11-19 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_remove_produto_loja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loja',
            name='avaliacoes',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='categorias',
        ),
        migrations.RemoveField(
            model_name='carrinho',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='carrinho',
            name='loja',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='loja',
        ),
        migrations.AddField(
            model_name='cliente',
            name='carrinho',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Carrinho'),
        ),
        migrations.DeleteModel(
            name='AvaliacaoLoja',
        ),
        migrations.DeleteModel(
            name='Loja',
        ),
    ]
