# Generated by Django 2.2.7 on 2019-11-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_auto_20191119_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categorias',
            field=models.ManyToManyField(related_name='produtos', to='website.Categoria'),
        ),
    ]
