# Generated by Django 2.2.7 on 2019-11-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_auto_20191120_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='qtd_limite',
            field=models.PositiveIntegerField(default=100, verbose_name='Quantidade limite'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='qtd_estoque',
            field=models.PositiveIntegerField(verbose_name='Quantidade em estoque'),
        ),
    ]
