# Generated by Django 2.2.7 on 2019-11-22 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_auto_20191121_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_vendas', to='website.Produto')),
            ],
            options={
                'verbose_name': 'Item da venda',
                'verbose_name_plural': 'Itens das vendas',
                'ordering': ['-update_at'],
            },
        ),
        migrations.RenameModel(
            old_name='ItensCarrinho',
            new_name='ItemCarrinho',
        ),
        migrations.AlterField(
            model_name='venda',
            name='produtos',
            field=models.ManyToManyField(related_name='vendas', through='website.ItemVenda', to='website.Produto'),
        ),
        migrations.DeleteModel(
            name='VendaProduto',
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='website.Venda'),
        ),
    ]
