# Generated by Django 2.2.7 on 2019-11-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_oferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='validade',
            field=models.DateTimeField(verbose_name='Validade'),
        ),
    ]
