# Generated by Django 2.2.7 on 2019-11-27 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_auto_20191125_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.AddField(
            model_name='cliente',
            name='enderecos',
            field=models.ManyToManyField(related_name='clientes', to='website.Endereco'),
        ),
        migrations.AddField(
            model_name='venda',
            name='endereco_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='website.Endereco'),
        ),
    ]
