# Generated by Django 2.2.7 on 2019-11-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_auto_20191127_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='banner',
        ),
        migrations.AddField(
            model_name='oferta',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='website/images/ofertas', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='is_banner',
            field=models.BooleanField(default=True, verbose_name='É banner?'),
            preserve_default=False,
        ),
    ]
