# Generated by Django 2.2.7 on 2019-11-28 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_auto_20191127_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='produto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='website.Produto'),
        ),
    ]
