# Generated by Django 2.2.7 on 2019-11-28 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_auto_20191128_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='website.Produto'),
        ),
    ]
