# Generated by Django 2.2.7 on 2019-11-29 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_auto_20191128_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrinho',
            name='valor',
        ),
    ]
