# Generated by Django 2.2.7 on 2019-11-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_remove_itemcarrinho_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrinho',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Valor'),
        ),
    ]
