# Generated by Django 2.2.7 on 2019-12-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_itemcarrinho_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
