# Generated by Django 2.2.7 on 2019-12-02 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0044_oferta_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='website/images', verbose_name='Imagem')),
                ('capa', models.BooleanField(verbose_name='É capa?')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='website.Produto')),
            ],
            options={
                'verbose_name': 'Imagem do Produtos',
                'verbose_name_plural': 'Imagens dos Produtos',
            },
        ),
    ]
