# Generated by Django 2.2.7 on 2019-12-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0045_imagemproduto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemproduto',
            name='capa',
            field=models.BooleanField(blank=True, default=False, verbose_name='É capa?'),
        ),
    ]
