# Generated by Django 2.2.7 on 2020-01-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_auto_20191202_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='valor_atual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Atual'),
        ),
    ]
