# Generated by Django 2.2.7 on 2020-01-02 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0047_produto_valor_atual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='valor_atual',
        ),
    ]
