# Generated by Django 2.2.7 on 2020-01-03 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0048_remove_produto_valor_atual'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemcarrinho',
            unique_together={('carrinho', 'produto')},
        ),
    ]
