# Generated by Django 2.2.7 on 2020-01-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0049_auto_20200103_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='numero_casa',
            field=models.PositiveIntegerField(verbose_name='Número'),
        ),
    ]
