# Generated by Django 3.0.2 on 2020-01-24 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200124_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{3}\\.\\d{3}\\.\\d{3}\\-\\d{2}$')], verbose_name='CPF'),
        ),
    ]
